nginx/unit

- auto/modules/ruby
Add -fdeclspec to NXT_RUBY_CFLAGS for Clang, if it's available.
Clang incorrectly reports 1 for __has_declspec_attribute(x) in
some cases, such as MacOS or Cygwin.  That causes ruby code to
break.  ruby added -fdeclspec to their CFLAGS in 2019 to
workaround this bug, since it enables __declspec() and therefore,
the compiler behavior matches what it reports.
Since we don't know what are all the architectures that trigger
the clang bug, let's add the flag for all of them (especially
since it should be harmless).
Add this workaround only at the time of configuring the ruby
module.  This way we don't clutter the global NXT_CFLAGS with an
unnecessary flag.
Link: unit bug <https://github.com/nginx/unit/issues/653>
Link: ruby bug <https://bugs.ruby-lang.org/issues/18616>
Link: LLVM bug …
> Workaround clang bug in __has_declspec_attribute()

- docs/changes.xml
- src/nxt_conf_validation.c
- src/nxt_http_return.c
- test/test_return.py
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
location = ":/?#[]@!$&'()*+,;=", expect = ":/?#[]@!$&'()*+,;="
def check_location(location, expect=None):
if expect is None:
expect = location
>       assert 'success' in self.conf(
{"return": 301, "location": location}, 'routes/0/action'
), 'configure location'
E       AssertionError: configure location
E       assert 'success' in {'detail': 'Unknown variable "" in the "location" value.', 'error': 'Invalid configuration.'}
E        +  where {'detail': 'Unknown variable "" in the "location" value.', 'error': 'Invalid configuration.'} = <bound method args_handler.<locals>.args_wrapper of <test_return.TestReturn object at 0x7f8789d01b50>>({'location': ":/?#[]@!$&'()*+,;=", 'return': 301}, …
```
> Add variables in "location"

- src/nxt_http_return.c
nxt_str_null() setted the loc.start pointer to NULL, which was
being passed to malloc(3) through nxt_debug().  That caused
Undefined Behavior, so we now pass an empty string.
> Fixed memcpy(dest, NULL, 0) Undefined Behavior.

- docs/changes.xml
- src/nxt_http_variables.c
- test/test_variables.py
This pull-request is for supporting a new variable called 'dollar' that can be
used for specifying _$_ 's in URIs etc. One such use case being $ sub-delimiters.
This pull-request comprises the following commits
- Var: added a $dollar variable that translates to a '$'.
- Tests: added tests for translating $sign into a literal $.
Wasn't sure if it _really_ needed tests as the current variable tests should
cover it, but added just a couple of new tests to ensure we are getting $'s
out. That commit can simply be dropped if it's not wanted.
So if you wanted to specify a URL like
https://example.com/path/15$1588/9925$2976.html
that would go in the unit config like
https://example.com/path/15${dollar}1588/9925${dollar}2976.html
All tests pass.
This relates to this …
> Add a $dollar variable that translates to a literal '$'

- docs/changes.xml
- src/ruby/nxt_ruby.c
- src/ruby/nxt_ruby.h
- test/test_ruby_application.py
Having the basename of the script pathname was incorrect.  While
we don't have something more accurate, the best thing to do is to
have it empty (which should be most of the time).
Fixes (git) commit 0032543fa65f454c471c968998190b027c1ff270,
which was 'Ruby: added the Rack environment parameter "SCRIPT_NAME".'.
Closes: <https://github.com/nginx/unit/issues/715>
> Ruby: fixed contents of SCRIPT_NAME.

- src/nxt_runtime.c
```
We renamed the options recently, with the intention of keeping the old
names as supported but deprecated for some time, before removal.  This
was done with the configure script options, but in the unitd binary, we
accidentally removed the old names, causing some unintended breakage.
Keep support for the old names, albeit with a deprecation message to
stderr, for some time, until we decide to remove them.
```
Fixes: 5a37171f733f ("Added default values for pathnames.")
Closes: <https://github.com/nginx/unit/issues/876>
Reported-by: @elrido
Acked-by: @lcrilly
Acked-by: @tippexs
Acked-by: @artemkonev
Cc: @andrey-zelenkov
Signed-off-by: @alejandro-colomar
> Added back deprecated options to unitd.

- src/nxt_socket_msg.h
As reported by @andypost on GitHub, if you try to build Unit on a system that uses musl libc (such as Alpine Linux) with clang then you get the following
clang -c -pipe -fPIC -fvisibility=hidden -O -W -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -fstrict-aliasing -Wstrict-overflow=5 -Wmissing-prototypes -Werror -g   -I src -I build/include   \
\
\
-o build/src/nxt_socketpair.o \
-MMD -MF build/src/nxt_socketpair.dep -MT build/src/nxt_socketpair.o \
src/nxt_socketpair.c
In file included from src/nxt_socketpair.c:8:
src/nxt_socket_msg.h:138:17: error: comparison of integers of different signs: 'unsigned long' and 'long' [-Werror,-Wsign-compare]
cmsg = CMSG_NXTHDR(&msg, cmsg))
^~~~~~~~~~~~~~~~~~~~~~~
/usr/include/sys/socket.h:358:44: note: expanded from macro 'CMSG_NXTHDR' …
> Fix build on musl libc with clang.

- src/java/nxt_jni_Response.c
- src/nxt_unit.c
We need to take into account the size of the nxt_unit_response_t structure itself when calculating where to start appending data to in memory.
> Java: fixed the calculation related to the response buffer.

- src/python/nxt_python_wsgi.c
This PR fixes an issue in Python 3.x whereby certain HTTP header field values where being incorrectly reported as non-ascii by the Python `.isascii()` method.
This PR comprises two patches
1)  Python: Do nxt_unit_sptr_get() earlier in nxt_python_field_value().
Does what it says on the tin. It's a preparatory patch that simply calls the `nxt_unit_sptr_get()` function earlier in `nxt_python_field_value()`.
2) Python: Fix header field values character encoding.
The meat and potatoes. This replaces the use of `PyUnicode_New()` with `PyUnicode_DecodeCharmap()`
This leaves the old code path in place for Python < 3.0. Python 2.7 has been deprecated for a few years, so hopefully at some point in the not _too_ distant future all the < Python 3.0 code can just get ripped out.
> Python: Fix an issue with HTTP header field values being incorrectly reported as non-ascii

- go/ldflags-darwin.go
This patch adds include paths for `libunit` installed via Homebrew only when built on Darwin (macOS). I don't know if Linux Homebrew uses the same paths, so this shouldn't get in the way in that edge case.
Small note, the syntax used on line 1 is the preferred syntax as of go1.18 and the old style of `// +build` should be `go fix`d across the repository in the future.
Fixes nginx/unit#967
> Go: Use Homebrew include paths

- src/nxt_conf_validation.c
Take the configuration as an example:
```
{
"rewrite": "`${foo + "
}
```
Before it was compiled in the router process with a simple error message:
```
failed to apply previous configuration
```
It should be checked in the controller process with the error message:
```
the previous configuration is invalid: "SyntaxError: Unexpected end of input in default:1" in the "rewrite" value.
```
> HTTP: added TSTR validation flag to the rewrite option.

- CONTRIBUTING.md
- README.md
Replaced Slack Community links with and redirected to GitHub Discussions as per this conversation https://github.com/nginx/unit/pull/1049#issuecomment-1881957291
> Replaced slack community links with GitHub Discussions

- go/ldflags-darwin.go
- go/ldflags-lrt.go
A RHEL 8 test was failing because it uses go1.16. The old style must be retained for backwards compat.
> Go: Add missing +build and go:build comments

- src/nxt_http_static.c
On GH, @tonychuuy reported an issue when using Units 'share' action they would get the following error in the unit log
2024/01/15 17:53:41 [error] 49#52 *103 file "/var/www/html/public/vendor/telescope/app.css" has changed while sending response to a client
This would happen when trying to serve files over a certain size and the requested file would not be sent.
This is due to a somewhat bogus check in
nxt_http_static_buf_completion()
I say bogus because it's not clear what the check is trying to accomplish and the error message is not entirely accurate either.
The check in question goes like
n = pread(file->fd, buf, size, offset);
return n;
...
if (n != size) {
if (n >= 0) {
/* log file changed error and finish */
}
/* log general error and finish */
}
If the number of bytes read is not …
> HTTP: Remove short read check in nxt_http_static_buf_completion()

- docs/changes.xml
- src/nodejs/unit-http/unit.cpp
- test/test_node_application.py
According to the Node.js documenation this variable
should only include numbering scheme.
Thanks to @dbit-xia.
Closes: https://github.com/nginx/unit/issues/1085
> Node.js: fixed "httpVersion" variable format

- src/nxt_conf_validation.c
- src/nxt_http_request.c
- src/nxt_router.h
- src/nxt_router_access_log.c
HTTP: enhanced access log with conditional filtering.
This feature allows users to specify conditions to control if access log
should be recorded. The "if" option supports a string and JavaScript code.
If its value is empty, 0, false, null, or undefined, the logs will not be
recorded. And the '!' as a prefix inverses the condition.
For example:
```
{
"access_log": {
"if": "`${new Date().getHours() < 22}`",
"path": "/path/access.log"
}
}
```
Or
```
{
"access_log": {
"if": "!`${new Date().getHours() >= 22}`",
"path": "/path/access.log"
}
}
```
If the current hour is less than 22, the logs will be recorded.
Closes: <https://github.com/nginx/unit/issues/594>
> HTTP: enhanced access log with conditional filtering.

- src/nxt_clone.c
- src/nxt_clone.h
- src/nxt_conf_validation.c
- src/nxt_isolation.c
This pull-request fixes an issue on arm64 when using user namespaces on Linux whereby the "container", "host" and "size" members of the uid/gidmaps could be corrupted. 
This would happen due to using nxt_int_t's to store these things, but on arm64 (and potentially others) these are 64bits. However there was an assumption that these would only be 32bits and due to setting these variables through a 32bit union alias, we would only set the four lower half bytes, leaving whatever was around in the upper half, giving some whacked out values.
It consists of the following five commits.
- Isolation: Add a new nxt_cred_t type
This adds a new type for holding uid/gids on Linux when using user namespaces.
- Configuration: Add a new CRED map type
This adds a new configuration map type that …
> Fix isolation uid/gidmaps on arm64

- src/nxt_conf.c
- src/nxt_conf.h
- src/nxt_conf_validation.c
- src/nxt_http_static.c
- src/nxt_router.c
We accept both \u0000socket-name and @socket-name as abstract Unix sockets.  The first one is passed to the kernel pristine, while the second is transformed '@'->'\0'.
The commit that added support for Unix sockets accepts both variants, but we internally stored it in the same way, using \u0000... for both.
We want to support abstract sockets transparently to the user, so that if the user configures unitd with '@', if we receive a query about the current configuration, the user should see the same exact thing that was configured.  So, this commit avoids the transformation in the internal state file, storing user input pristine, and we only transform the '@' for a string that will be used internally (not user-visible).
This commit (indirectly) fixes a small bug, where we created abstract …
> Config: Store abstract sockets with @ internally

- docs/changes.xml
- src/nodejs/unit-http/http.js
- src/nodejs/unit-http/http_server.js
- test/node/options/app.js
- test/test_node_application.py
Closes https://github.com/nginx/unit/issues/1043
Unit-http have not kept up with the signature of nodejs's http package development. Nodejs allows an optional `options` object to be passed to the `createServer` function, we didn't. This resulted in function signature errors when user code that did make use of the options arg tried to call unit's replaced function.
This change changes the signature to be more in line with how nodejs does it discarding it and printing a message to stderr so it shows up in unit logs.
> fix: Take options as well as requestListener

- docs/man/man8/unitd.8.in
- src/nxt_file.c
- src/nxt_file.h
- src/nxt_listen_socket.c
- src/nxt_runtime.c
- src/nxt_runtime.h
- tools/unitc
This PR comprises four patches...
1) Add nxt_file_chown().
This adds a wrapper around [chown(2)](https://man7.org/linux/man-pages/man2/chown.2.html). It's slightly long-winded due to using the thread safe versions ([getpwnnam_r(3)](https://man7.org/linux/man-pages/man3/getpwnam_r.3.html) & [getgrnam_r(3)](https://man7.org/linux/man-pages/man3/getgrnam_r.3.html)) of [getpwnam(3)](https://man7.org/linux/man-pages/man3/getpwnam.3.html) & [getgrnam(3)](https://man7.org/linux/man-pages/man3/getgrnam.3.html).
2) Allow to set the permissions of the Unix domain control socket.
This allows the user to set the file mode, owner & group of the UNIX domain control socket via three new options; `--control-mode`, `--control-user` & `--control-group`.
Any combination of the above can be used. `mode` is …
> Enable the setting of the file mode, owner and group of the UNIX domain control socket

- src/nodejs/unit-http/http_server.js
Functionally identical, but marginally more idiomatic.
Refines: fbeb2065b180e2376088387ee150d3975dc08cd5
cc: @javorszky
For reference, Node's console docs are here: https://nodejs.org/docs/latest-v20.x/api/console.html
`console.warn` is an alias for `console.error`, and `console.error` is documented as: "Prints to stderr with newline." The `console` global has been present since the very earliest releases of Node.
> Node.js: Use console.warn instead of stderr.write

- pkg/docker/Dockerfile.python3.12
Forgotten in
<https://github.com/nginx/unit/commit/c3af21e970ca3c822004cfda7c5b56ec07d99da9>
> Docker: Switch python3.12 to using github

- src/nxt_conn_write.c
This is a simple temporary fix (doesn't address the underlying problem) for an issue reported by a user on GitHub whereby downloading of files from a PHP application would cause the router process to crash.
This is actually a generic problem that will affect anything sending data via nxt_unit_response_write().
This is just a simple fix for the 1.32 release, after which the full correct fix will be worked out.
> Avoid a segfault in nxt_conn_io_sendbuf()

- docs/changes.xml
- src/nxt_http_js.c
- src/nxt_http_variables.c
- src/nxt_js.c
- src/nxt_var.c
- src/nxt_var.h
This PR is to introduce the feature of njs variable access. Here are 3 commits:
1. Generalize nxt_var_cache_value() to get variables via string names beside the reference index.
2. Introduce nxt_var_get() to access variables via string names, it'll be used in the next commit of access variables with njs.
3. njs variable access support.
Note, in the configuration, option values like `some $uri text`, and the part `uri` which is a variable name turned into an internal reference index for performance optimization. For the new feature, users can write JS code like `${uri}` in the configuration, the script is parsed with njs library, so it can only access variable with a string name `uri`.
So we need to support two ways of accessing variables: ref index and string name.
> NJS variable access support.

- pkg/docker/template.Dockerfile
This allows to use /dev/stdout as application logs if users choose to do so.
Fixes https://github.com/nginx/unit/issues/982
> Docker: redirect logs to stderr

- src/nodejs/unit-http/loader.js
- src/nodejs/unit-http/loader.mjs
Closes: <https://github.com/nginx/unit/issues/1013>
In that particular issue the compiled nuxt files end up importing the http module as `node:http` rather than `http` only. This bypasses unit's custom loader implementation which only check for the `http` or `unit-http` modules, and their websocket counterparts.
This changeset adds replace sources for both the `node:http` and `node:websocket` import signatures.
> Add additional replace rules for node:* modules to custom unit node loaders.

- pkg/docker/Dockerfile.go1.20
- pkg/docker/Dockerfile.go1.21
- pkg/docker/Dockerfile.jsc11
- pkg/docker/Dockerfile.minimal
- pkg/docker/Dockerfile.node18
- pkg/docker/Dockerfile.node20
- pkg/docker/Dockerfile.perl5.36
- pkg/docker/Dockerfile.perl5.38
- pkg/docker/Dockerfile.php8.2
- pkg/docker/Dockerfile.python3.11
- pkg/docker/Dockerfile.python3.12
- pkg/docker/Dockerfile.ruby3.2
- pkg/docker/Dockerfile.wasm
- pkg/docker/template.Dockerfile
Saves on the order of 10 MBs of transfer for each build.
We call `rm -rf /usr/src/unit` later in this step, so the full repo has never appeared in our published images anyway.
Related to @thresheek's work in #1131
> Docker: Shallow clone the Unit repo

- pkg/docker/Dockerfile.go1.21
- pkg/docker/Dockerfile.go1.22
- pkg/docker/Dockerfile.jsc11
- pkg/docker/Dockerfile.minimal
- pkg/docker/Dockerfile.node20
- pkg/docker/Dockerfile.node21
- pkg/docker/Dockerfile.perl5.36
- pkg/docker/Dockerfile.perl5.38
- pkg/docker/Dockerfile.php8.2
- pkg/docker/Dockerfile.php8.3
- pkg/docker/Dockerfile.python3.11
- pkg/docker/Dockerfile.python3.12
- pkg/docker/Dockerfile.ruby3.3
- pkg/docker/Dockerfile.wasm
- pkg/docker/Makefile
- Go: Drop 1.20, Add 1.22
- Node: Drop 18, Add 21
- PHP: Add 8.3
- Ruby: Add 3.3
Perl and Python are still up-to-date with upstream releases
Regenerating the Dockerfiles also picks up the logging change from
183a1e9d634ae2fb129ce98f1ca8a16cbfdeac99
This replicates and replaces @thresheek's work in #1127
> Docker: Update versions of Go, Node, PHP, Ruby

- pkg/deb/Makefile.wasm
- pkg/rpm/Makefile.wasm
Mostly mirrors the method used in the dockerfiles
Tested on RHEL 8, RHEL 9, Amazon Linux 2, Ubuntu 20.04, Ubuntu 22.04, Ubuntu 23.10.
Compared to `wasm` module, for `wasm-wasi-component` wasmtime and dependencies are built twice: once for debug and once for non-debug build. 
Also, both resulting module shared objects ship their own copy of wasmtime, making it three copies of wasmtime (one 11.0.1 and two 17.0.1) shipped in the package.
> Packaging for wasm wasi component module

- auto/modules/wasm-wasi-component
Rather than calling make itself to build nxt_unit.o make nxt_unit.o a dependency of the main module build target.
After this patch
```
$ make
cc -c -pipe -fPIC -fvisibility=hidden -O0 -W -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wmissing-prototypes  -g   -I src -I build/include   \
\
\
-o build/src/nxt_unit.o \
-MMD -MF build/src/nxt_unit.dep -MT build/src/nxt_unit.o \
src/nxt_unit.c
```
Compared to before
```
$ make
make build/src/nxt_unit.o
make[1]: Entering directory '/home/andrew/src/unit'
cc -c -pipe -fPIC -fvisibility=hidden -O0 -W -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wmissing-prototypes  -g   -I src -I build/include   \
\
\
-o build/src/nxt_unit.o \
-MMD -MF build/src/nxt_unit.dep -MT build/src/nxt_unit.o \
src/nxt_unit.c
```
> Wasm-wc: Add nxt_unit.o as a dependency in the auto script

- .github/workflows/ci.yml
The info and above errors should be more than enough for debugging
failures in GitHuB Actions CI.
> Remove debug from builds and tests

- pkg/deb/Makefile.wasm
- pkg/rpm/Makefile.wasm
This extends the approach used for debian-based packages in 3f805bc64e28 to rpm as well.  Notable change for both deb and rpm packaging is to use CFLAGS as defined in the build/Makefile, and not pass them from the environment which might not be there (as is the case for rpm).
While at it, stop passing CFLAGS in the install phase, as it should no longer invoke builds (see d54af163c46b).
The rpm part was overlooked in 7a6405566c0, since testing was not done on the platforms where problem manifested itself, notably Amazon Linux 2023 and Fedora 38+.
> Packages: Pass CFLAGS to compile wasm modules on all packaging targets

- .github/workflows/ci.yml
`setup-php` action was fixed to add embed SAPI for older versions of PHP
> Add PHP 8.2 and 8.1 to test matrix

- .github/workflows/ci.yml
Removes deprecation notices on actions builds. v5 updates the version of
node and `cache: false` disables the errors related to not finding a
go.sum
> Update setup-go to v5

- auto/modules/wasm-wasi-component
-o is not available on macOS 12.7 at least, and it's what homebrew seems to support still.
Also, the proposed switch seems to be used already in the codebase.
> Wasm-wc: use more common uname switch to get operating system name

- src/nxt_conf.c
If we compile Unit with -Wstrict-overflow=5 (as we do with clang) then we get the following warning
```
cc -c -pipe -fPIC -fvisibility=hidden -O0 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wstrict-overflow=5 -Wmissing-prototypes  -g   -I src -I build/include   \
\
\
-o build/src/nxt_conf.o \
-MMD -MF build/src/nxt_conf.dep -MT build/src/nxt_conf.o \
src/nxt_conf.c
src/nxt_conf.c: In function ‘nxt_conf_json_parse_value’:
src/nxt_conf.c:1444:5: warning: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Wstrict-overflow]
1444 |     if (nxt_fast_path((ch - '0') <= 9)) {
|
```
Does this actually cause an issue?... well, yes. Using this minimal test config to show the problem
```json
{
"listeners": {
"[::1]:8080": {
"pass": --100
}
}
}
```
With …
> Fix check in nxt_conf_json_parse_value()

- src/nxt_router.c
- src/nxt_var.c
These commits fix a couple of issues found by the clang static analyser.
- Var: Remove a dead assignment in nxt_var_interpreter()
The first removes a dead assignment whereby we store the return from a nxt_cpymem() bu then return from the function before doing anything further with it.
- Avoid potential NULL pointer dereference in nxt_router_temp_conf()
The second fixes a potential NULL pointer dereference.
> Clang static analyser fixes

- .github/workflows/ci.yml
To enable tests that require privileged root access, this commit tests with `sudo`. The Java and Python jobs have additional permissions issues, so they are also configured and made with `sudo`.
A small permissions fix is required before running tests to allow non-root users to execute within the `/home/runner` directory.
This change also removes the custom directories that were required without root access.
> Test with root access in GitHub workflows

- .github/workflows/ci.yml
This adds a GitHub CI workflow for the new wasm-wasi-component language module.
Some things of note.
1) We need to special case 'wasm-wasi-component' in the 'Output build
metadata' section as we are splitting the module names on '-' to
split them into name and version.
2) Apart from needing to tell bindgen about the njs include paths, we
also need to explicitly specify which version of clang to use to
work around an [issue](https://gitlab.freedesktop.org/mesa/mesa/-/issues/7268) with multiple versions of clang installed.
> Add GitHub workflow for wasm-wasi-component

- .mailmap
I changed a setting and now GitHub will recognize both the legacy numberless version, and the newer version with UserID.
The with-UserID version will be used by the any changes stemming from the GitHub GUI.
> .mailmap: Map Dylan's 2nd GitHub address

- src/nxt_var.c
The variables accessed with JS template literal should be not cacheable. Since it is parsed by njs engine, Unit can't create indexes on these variables for caching purpose. For example:
{
"format": "`{bodyLength:\"${vars.body_bytes_sent}\",status:\"${vars.status}\"}\n`"
}
The variables like the above are not cacheable.
Closes: https://github.com/nginx/unit/issues/1169
> Var: Fix cacheable issue for njs variable access.

- README.md
On Red Hat based distributions use dnf instead of yum, dnf superseded yum a long time ago.
Also fix the security-alert email link to actually open up in an email client, rather than it trying to make the email link a part of the Unit repository URL.
> A couple of README updates

- test/test_njs.py
Reproduces issue https://github.com/nginx/unit/issues/1169.
> Tests: NJS cacheable variables with access log

- README.md
This adds a 'repostatus' badge, set to 'active', as per F5/NGINX OSS
policy...
It also adds a GitHub workflows badge that shows the current state of our
CI builds and points to the Unit workflows page.
You can see what they look like [here](https://github.com/ac000/unit/blob/ci-badge/README.md).
Note: For the workflows badge (the second one) the 'CI' text (on the
black background) can be changed.
> Add status badges to the README

- auto/cc/test
Currently Unit doesn't specify any specific C standard for compiling and will thus be compiled under whatever the compiler happens to default to.
For most recent'ish compilers that will be gnu11/17 (C11/17 + GNU extensions).
For some of the oldest still-supported systems, e.g RHEL/CentOS 7 and Debian 8 that will be gnu90 (with GCC 4.8.x).
Up until now this hasn't really been an issue and we have been able to use some C99 features that are implemented as GNU extensions in older compilers, e.g
-  designated initializers
-  flexible array members
-  trailing comma in enum declaration (compiles with -std=c89, warns with -std=c89 -pedantic)
-  snprintf(3)
-  long long (well we test for it but don't actually use it)
-  bool / stdbool.h
-  variadic macros
However there are a couple of C99 …
> Explicitly build with -std=gnu11 (C11 with GNU extensions)

- auto/modules/wasm-wasi-component
- src/wasm-wasi-component/src/lib.rs
This PR comprises two fixes
- Have cargo run if any of the language modules dependencies change, e.g (`src/wasm-wasi-component/src/lib.rs`)
Missing dependencies in the Makefile
- Fix restarting wasm-wasi-component applications.
Terminating applications must call `exit(2)`
> Some wasm-wasi-component related fixes

- test/unit/applications/tls.py
OpenSSL 3.2.0 generates X.509v3 certificates by default. These certificates, even self-signed, cannot sign other certificates unless "CA:TRUE" is explicitly set in the basicConstraints extension. As a result, tests attempting this are currently failing.
Fix is to provide "CA:TRUE" in the basicConstraints for self-signed root certificates used in "openssl ca" commands.
> Tests: compatibility with OpenSSL 3.2.0

- src/nxt_conf_validation.c
This is to improve error messages for response headers configuration. Take the configuration as an example:
```
{
"response_headers": {
"a": "$b"
}
}
```
Previously, when applying it the user would see this error message:
```
failed to apply previous configuration
```
After this change, the user will see this improved error message:
```
the previous configuration is invalid: Unknown variable "b" in the "a" value
```
> HTTP: Added variable validation to the response_headers option

- test/test_response_headers.py
For more information please see https://github.com/nginx/unit/pull/1191
> Tests: error report corrected for unknown variables in "response_headers"

- src/nxt_h1proto.c
- src/nxt_http.h
- src/nxt_http_parse.c
- src/nxt_http_parse.h
- src/nxt_http_rewrite.c
Previously, proxy request was constructed based on the `r->target` field. However, r->target will remain unchanged in the future, even in cases of URL rewriting.
To accommodate this, I refactored the handling of the proxy target.
> HTTP: Refactoring nxt_h1p_peer_header_send()

- src/test/nxt_http_parse_test.c
This issue was introduced in the commit 64934e5.
> HTTP: Fixed missed parsing test

- README.md
I noted that our Docker instructions don't provide a complete quickstart, and leaves the user thinking about what additional steps need to be taken to host their application. While this isn't too hard to figure out on it's own I find that just having the instruction there saves time otherwise spent looking at examples and finding/reading the Dockerfile.
Additionally, after stumbling on our deprecated WASM functionality before the supported component; I found it prudent to show our WASM documentation front and center. Hopefully this will spare potential users any confusion they get finding the wrong thing first.
Finally, I wanted to point out the configuration docs in their own section, because I missed the single inline link we have to them the first two times I read through our Readme.
> Add key points to Readme.

- src/nxt_conf.c
- src/nxt_conf.h
- src/nxt_conf_validation.c
- src/nxt_controller.c
- src/nxt_http.h
- src/nxt_http_route.c
- src/nxt_http_variables.c
- src/nxt_isolation.c
- src/nxt_js.c
- src/nxt_php_sapi.c
- src/nxt_router.c
- src/nxt_router_access_log.c
- src/nxt_unit.c
- src/nxt_upstream.c
- src/nxt_upstream_round_robin.c
This patch series marks various pointer function arguments as `const` in the configuration sub-system.
The main impetus of this was to convert a bunch of
```c
static nxt_str_t ...
```
variable declarations to
```c
static const nxt_str_t ...
```
Having these _only_ `static` seems a bit weird, given what that means and that they we're really being treated as string literals.
Making them `static const` really makes them  const, and remove the thread safety issue, in that if you try to write to them then the compiler will yell at you!
There is also precedent for this in Unit as we already had
```
src/nxt_conf_validation.c:2032:    static const nxt_str_t  wsgi = nxt_string("wsgi");
src/nxt_conf_validation.c:2033:    static const nxt_str_t  asgi = nxt_string("asgi"); …
```
> Pointer constification

- .github/workflows/check-whitespace.yaml
If it fails you can check the 'git log --check' output of the workflow to see what the issue is. E.g
--- 93ec0133 Oops...
README.md:1: trailing whitespace.
+# NGINX Unit
> Add a GitHub workflow to check for whitespace issues

- auto/modules/wasm
Since commit 0b5223e1c ("Disable strict-aliasing in clang by default") we explicitly always build with -fno-strict-aliasing so there's no need to set it independently in auto/modules/wasm
> No need to explicitly set -fno-strict-aliasing in the wasm module now

- auto/modules/wasm
- src/nxt_http_route.c
- src/nxt_upstream.h
- src/nxt_upstream_round_robin.c
- src/python/nxt_python.h
Declaring a 0-sized array (e.g 'char arr[0];') as the last member of a
structure is a GNU extension that was used to implement flexible array
members (FAMs) before they were standardised in C99 as simply '[]'.
The GNU extension itself was introduced to work around a hack of
declaring 1-sized arrays to mean a variable-length object. The advantage
of the 0-sized (and true FAMs) is that they don't count towards the size
of the structure.
Unit already declares some true FAMs, but it also declared some 0-sized
arrays.
Converting these 0-sized arrays to true FAMs is not only good for
consistency but will also allow better compiler checks now (as in a C99
FAM *must* be the last member of a structure and the compiler will warn
otherwise) and in the future as doing this fixes a bunch of warnings …
> Convert 0-sized arrays to true flexible array members

- auto/modules/perl
When we added -fno-strict-overflow to the CFLAGS back in c1e3f02f9 ("Compile with -fno-strict-overflow") we inadvertently broke building the Perl language module with clang, e.g
```
$ make
CC     build/src/perl/nxt_perl_psgi-perl.o
clang: error: argument unused during compilation: '-fno-strict-overflow' [-Werror,-Wunused-command-line-argument]
```
This is due to for example on Apline
```
$ perl -MExtUtils::Embed -e ccflags
-D_REENTRANT -D_GNU_SOURCE -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
```
Where on clang the -fwrapv causes the -fno-strict-overflow to be discarded resulting in the above error.
We can get around that by simply appending -Qunused-arguments to the Perl CFLAGS.
This fixes things for _some_ systems, …
> Fix building the Perl language module with clang (on some systems)

- tools/unitctl/Cargo.lock
- tools/unitctl/README.md
- tools/unitctl/unit-client-rs/Cargo.toml
- tools/unitctl/unit-client-rs/src/control_socket_address.rs
- tools/unitctl/unit-client-rs/src/lib.rs
- tools/unitctl/unit-client-rs/src/unit_client.rs
- tools/unitctl/unit-client-rs/src/unitd_cmd.rs
- tools/unitctl/unit-client-rs/src/unitd_docker.rs
- tools/unitctl/unit-client-rs/src/unitd_instance.rs
- tools/unitctl/unit-client-rs/src/unitd_process.rs
- tools/unitctl/unit-openapi/.gitattributes
- tools/unitctl/unitctl/src/cmd/edit.rs
- tools/unitctl/unitctl/src/cmd/execute.rs
- tools/unitctl/unitctl/src/cmd/import.rs
- tools/unitctl/unitctl/src/cmd/instances.rs
- tools/unitctl/unitctl/src/cmd/listeners.rs
- tools/unitctl/unitctl/src/cmd/status.rs
- tools/unitctl/unitctl/src/main.rs
- tools/unitctl/unitctl/src/requests.rs
- tools/unitctl/unitctl/src/unitctl.rs
- tools/unitctl/unitctl/src/wait.rs
This PR adds functionality to the CLI to support its existing functionality used with Docker deployments of Unit. In addition to that, a new subcommand is added that offers a procedure to deploy any unit docker image with user defined mounts for the control socket and any application of choice. Finally, unitctl codebase is refactored to simply handling of async futures, relying on a standard provided runtime instead of attempting to maintain a custom future executor. Tests are added and updated as well.
> Docker via CLI

- src/nxt_h1proto.c
- src/nxt_http_rewrite.c
- test/test_python_application.py
- test/test_variables.py
1. <del>Another implementation of proxy request creation.</de.
2. Made the `$request_uri` constant.
3. Passed constant `REQUEST_URI` to applications.
Need to separate the PR after tests pass.
Here's a manual test.
```
{
"listeners": {
"*:8080": {
"pass": "routes/a"
},
"*:8081": {
"pass": "routes/b"
}
},
"routes": {
"a": [
{
"action": {
"rewrite": "/foo.php",
"proxy": "http://127.0.0.1:8081"
}
}
],
"b": [
{
"action": {
"rewrite": "/index.php",
"pass": "applications/app"
}
}
]
},
"applications": {
"app": {
"type": "php",
"root": "/www",
"index": "index.php"
}
}
}
```
```
<?php
phpinfo();
```
```
> curl http://127.1:8080
$_SERVER['REQUEST_URI'] => /foo.php
```
> HTTP: Ensure REQUEST_URI immutability.

- .github/workflows/unitctl.yml
- tools/unitctl/unit-client-rs/src/unitd_configure_options.rs
* fix a few misspellings in unitctl CI workflow
* add unit testing job
* disable one test 
* add additional triggers for CI
About the disabled test: It tests that the CLI can run a local copy of the unitd binary. This would require a custom image to run in CI. If we find it necessary, I am happy to work on it as an additional changeset.
> Add unit testing to Unitctl CI workflow

- .mailmap
You can always see the original names/addresses used by passing --no-mailmap to the various git commands.
See gitmailmap(5)
> .mailmap: Add an entry for Ava's GitHub address

- .github/workflows/ci-dev-distro-compiler.yaml
- .mailmap
This adds a workflow for building Unit under Fedora Rawhide and Alpine
Edge with both GCC and Clang.
These are the development branches from which releases are cut.
This usually consists of the latest versions of software and will
hopefully catch new compiler issues and API breakages in the various
languages we support.
With Alpine and Clang that also gives us musl libc + clang coverage.
On Alpine we don't build the wasm and wasm-wasi-component modules,
mainly as this would require messing around with all the rust stuff and
building wasmtime from source (as there's no musl libc based packages)
and the wasm module is pretty small, any new compiler issues would
hopefully show up in the rest.
We _do_ build the wasm module with gcc and clang on Fedora. But not
wasm-wasi-component in the …
> Add GitHub workflows for extra coverage

- pkg/contrib/Makefile
The lists of files being unpacked are mostly useless but take a significant amount of lines and bytes in e.g. CI jobs.  E.g. in rhel9 packaging job, it's 39680 lines just for the unpacking of wasmtime-v11.0.1-src, as compared to total 48945 lines of output.
> contrib: be quiet on unpack

- src/nxt_tstr.c
- src/nxt_tstr.h
- src/wasm/nxt_wasm.c
- `tstr: Constify the 'str' parameter to nxt_tstr_compile()`
Just as the commit subject says, this constifies the `str` parameter to `nxt_tstr_compile()`
I have some code like
```c
static nxt_str_t        accept_enc_str =                                    
nxt_string("$header_accept_encoding");      
static const nxt_str_t  comps_str = nxt_string("compressors");              
static const nxt_str_t  mimes_str = nxt_string("types");
```
Looking at it, you may wonder why the first one isn't `static const`, well it can be after this patch...
- `wasm: Add a missing 'const' qualifier in nxt_wasm_setup()`
`filesystem_str` can be defined as `static const` rather than just `static`
> Make a couple of things 'const'

- test/conftest.py
First patch needed to format error string message to show temporary dir path, while second patch needed to print unit.log in case of unmount error.
> tests: unmount related fixes

- README.md
I need to update this with the NGINX color code.
I don't claim to know any/all PR requirements -- I'm using this as a learning experience.
ref https://github.com/nginx/unit-docs/issues/150
> Add a GitHub discussions badge to the README

- tools/unitc
This patch does a number of things to help when failing to apply a new
configuration.
* The error body from the Unit control API is displayed which can have
useful troubleshooting information (when the version of curl supports it).
* When using the EDIT option, the temporary file with unapplied changes is
preserved so that the user can edit it again without losing their work.
* Editing JavaScript modules no longer requires that module to have been
enabled.
* Failure to apply edited JavaScript modules now rolls-back to the previous
configuration instead of deleting the module.
> Tools: improved error handling for unitc

- .github/workflows/ci.yml
Commit 4fc50258b ("ci: Be more specific when to run the main Unit checks") limited when the checks for the main ci run, on pushes to master.
It should have done the same for pull-requests.
> ci: Limit when to run checks on pull-requests

- src/nxt_http_parse.c
oss-fuzz Issue [68458](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68458).
My Old PR https://github.com/nginx/unit/pull/1292
> http: fix use-of-uninitialized-value bug

- .github/workflows/unitctl.yml
* title of release is modified to read "unitctl-..."
* body text added to elaborate that this is only a release for unitctl
* explanation added for where users can find releases of Unit itself
Example release:
manual trigger: https://github.com/avahahn/unit/releases/tag/999.1.2-thebeesknees
tag trigger: https://github.com/avahahn/unit/releases/tag/9.9.10
> differentiate unitctl releases

- auto/make
- auto/shmem
- configure
- src/nxt_cgroup.c
- src/nxt_controller.c
- src/nxt_fs.c
- src/nxt_fs.h
- src/nxt_isolation.c
- src/nxt_listen_socket.c
- src/nxt_main_process.c
- src/nxt_port_memory.c
- src/nxt_runtime.c
- src/nxt_unit.c
Here are all the patches I prepared, in a single PR, tu allow you to understand the global idea I have in mind.
Feel free to apply this branch, or apply refactoring patches separately.
Cc: @ac000 , @andypost, @lcrilly , @thresheek 
Supersedes: <https://github.com/nginx/unit/pull/1227>
Closes: <https://github.com/nginx/unit/issues/742>
> mkdir -p $runstatedir at run time, not install time (round 2)

- tools/unitctl/Cargo.lock
- tools/unitctl/README.md
- tools/unitctl/unitctl/Cargo.toml
- tools/unitctl/unitctl/src/cmd/mod.rs
- tools/unitctl/unitctl/src/cmd/save.rs
- tools/unitctl/unitctl/src/main.rs
- tools/unitctl/unitctl/src/unitctl.rs
Currently implemented is a `unitctl` subcommand that saves Unitd configuration to a tarball. This is the first step in addressing #1317. 
Yet to be implemented is support for saving NJS modules or certificates. The code enclosed will be trivial to extend to support that later. Until then, #1317 should remain open.
> unitctl export subcommand

- src/nxt_conf_validation.c
- src/nxt_h1proto.c
- src/nxt_http.h
- src/nxt_http_chunk_parse.c
- src/nxt_http_parse.h
- src/nxt_http_request.c
- src/nxt_router.c
- src/nxt_router.h
A draft patch for the MVP of this feature.
Internally, I transferred the chunked request to content-length request since the application process can't handle chunked request now.
conf.json
```
{
"listeners": {
"*:8080": {
"pass": "routes"
}
},
"routes": [
{
"action": {
"pass": "applications/app"
}
}
],
"applications": {
"app": {
"type": "python",
"path": "/www",
"module": "wsgi"
}
}
}
```
/www/wsgi.py
```
def application(environ, start_response):
content_length = int(environ.get('CONTENT_LENGTH', 0))
body = bytes(environ['wsgi.input'].read(content_length))
start_response(
'200', [],
)
return [body]
```
```
> curl -X POST -d 'hello' -H "Transfer-Encoding: chunked" http://127.0.0.1:8080 -v
Note: Unnecessary use of -X or --request, POST is already inferred.
* Rebuilt URL to: …
```
> Support chunked request bodies

- pkg/docker/Makefile
A few docker-related changes:
- Moved debian-based images to Bookworm
- Node and perl versions are updated to the latest
- Rust/rustup used for wasm variant are updated to the latest
> Docker-related updates

- src/perl/nxt_perl_psgi.c
- src/test/nxt_clone_test.c
These somehow got missed in my previous set of patches to constify the likes of
```c
static nxt_str_t  foo_str = nxt_string("foobar");
```
**NOTE:**  There is a also a [patch](https://github.com/ac000/unit/commit/cae58b4b57a528f99791f8670a79756c76342021) do similar in the Python language module which is waiting for https://github.com/nginx/unit/pull/1336 to be merged.
> Constify some missed static local variables (in src/perl, src/test)

- src/nxt_tstr.c
This issue was found with oss-fuzz.
```
==18420==WARNING: MemorySanitizer: use-of-uninitialized-value
#0 0x55dd798a5797 in nxt_vsprintf unit/src/nxt_sprintf.c:163:31
#1 0x55dd798d5bdb in nxt_conf_vldt_error unit/src/nxt_conf_validation.c:1525:11
#2 0x55dd798dd4cd in nxt_conf_vldt_var unit/src/nxt_conf_validation.c:1560:16
#3 0x55dd798dd4cd in nxt_conf_vldt_if unit/src/nxt_conf_validation.c:1592:16
#4 0x55dd798d55f4 in nxt_conf_vldt_object unit/src/nxt_conf_validation.c:2815:23
#5 0x55dd798d6f84 in nxt_conf_vldt_access_log unit/src/nxt_conf_validation.c:3426:11
#6 0x55dd798d55f4 in nxt_conf_vldt_object unit/src/nxt_conf_validation.c:2815:23
#7 0x55dd798d47bd in nxt_conf_validate unit/src/nxt_conf_validation.c:1421:11
#8 0x55dd79871c82 in LLVMFuzzerTestOneInput …
```
> tstr, conf: Ensure error strings are nul-terminated

- src/nxt_conf_validation.c
- src/python/nxt_python.c
- test/python/factory/wsgi.py
- test/test_python_factory.py
This pr adds the factory support in python languange. By introducing new option as "factory" which can be set as true or false, if true, the callable will be interpreted as factory otherwise not
> Python: Add 'factory' support

- src/nxt_controller.c
Previously, the certificate deletion only handled string type certificates, causing issues when certificates were specified as an array in the configuration.
> Fix certificate deletion for array type certificates

- auto/modules/wasm-wasi-component
The first patch is just a clean up patch that fixes some indentation.
The second patch copies the wasm-wasi-component .so into `build/lib/unit/modules/` with the right name. This matches the behaviour of the other language modules and is needed by things like the pytests.
> Copy the wasm-wasi-component module into build/lib/unit/modules/ as part of the build process

- tools/unitctl/README.md
- tools/unitctl/unitctl/src/cmd/applications.rs
- tools/unitctl/unitctl/src/cmd/edit.rs
- tools/unitctl/unitctl/src/cmd/execute.rs
- tools/unitctl/unitctl/src/cmd/import.rs
- tools/unitctl/unitctl/src/cmd/listeners.rs
- tools/unitctl/unitctl/src/cmd/save.rs
- tools/unitctl/unitctl/src/cmd/status.rs
- tools/unitctl/unitctl/src/main.rs
- tools/unitctl/unitctl/src/unitctl.rs
- tools/unitctl/unitctl/src/unitctl_error.rs
- tools/unitctl/unitctl/src/wait.rs
This commit refactors the CLI code to accept
multiple instances of the control socket flag.
All subcommands except for edit and save now
support being run against multiple specified
instances of unitd.
* control_socket_addresses CLI field is now a vector
* centralize error related logic into the error module
* wait_for_socket now returns a vector of sockets. all sockets in vector are waited upon and validated
* extraneous code is removed
* applications, execute, import, listeners, and status commands all run against N control sockets now
* edit and save commands return error when run against a single control socket
Fixes: #1318
> Enable Multi Socket Support

- pkg/contrib/Makefile
FreeBSD introduced sha512sum binary in version 14, but with slightly incompatible flags as compared to Linux version.  This change makes it work in both worlds.
> contrib: make sha512sum check compatible with FreeBSD implementation

- src/nxt_application.c
- src/nxt_application.h
- src/nxt_main_process.c
- src/nxt_status.c
- test/unit/status.py
This pull-request comprises five commits with the overall goal of showing what language modules Unit has loaded _and_ from where, under the `/status` control API endpoint.
E.g
```json
{
"modules": {
"python": [
{
"version": "3.12.3",
"lib": "/opt/unit/modules/python.unit.so"
},
{
"version": "3.12.1",
"lib": "/opt/unit/modules/python-3.12.1.unit.so"
}
],
"wasm": {
"version": "0.1",
"lib": "/opt/unit/modules/wasm.unit.so"
},
"wasm-wasi-component": {
"version": "0.1",
"lib": "/opt/unit/modules/wasm_wasi_component.unit.so"
}
},
...
}
```
This could be a useful debugging aid.
Patches
- status: Constify a bunch of local variables
Preparatory patch that `static const`'s a bunch of nxt_string()'s before I add some more...
- status: Use a variable to represent the status member index
Preparatory …
> Show loaded modules under '/status'

- src/nxt_buf.h
As the comment for 'Memory-only buffers' says
"... it is equal to offsetof(nxt_buf_t, file.pos)"
and
"... that is it is nxt_buf_t without file and mmap part"
Those are at odds with each other, 'file.pos' comes _after_ 'file' in the nxt_buf_t structure.
Fix the 'offset()' bit of the comment to reflect that and to match the relevant macro
```c
#define NXT_BUF_MEM_SIZE        offsetof(nxt_buf_t, file)
```
> Fix a comment typo for 'Memory-only buffers' in src/nxt_buf.h

- src/nxt_status.c
This was missed from my recent status-modules patches.
> status: Add a missing check for potential NULL

- .github/workflows/cifuzz.yml
- fuzzing/README.md
- fuzzing/build-fuzz.sh
- fuzzing/nxt_http_controller_fuzz.c
- fuzzing/nxt_http_h1p_fuzz.c
- fuzzing/nxt_json_fuzz.c
Continuing the fuzzing integration: https://github.com/nginx/unit/pull/1291.
Adding [cifuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration) for checking build failures and PR fuzzing.
Using the main [example](https://google.github.io/oss-fuzz/getting-started/continuous-integration/#integrating-into-your-repository) provided by the OSS-Fuzz team, with an updated time of only 300 seconds.
> fuzzing: cifuzz workflow, fix oss-fuzz issues, updated dir name

- tools/unitctl/README.md
I wanted the unitctl readme to elaborate on the how and the limitations of each function that the tool offers... not just a one-line description and an example. I added more text to each section. Please leave feedback if you feel there are any significant details left out.
> tools/unitctl: Elaborate on features in unitctl readme.

- tools/unitctl/unitctl/src/unitctl.rs
After figuring out what and how clap deals with input enums and how those enums end up being serialised to the terminal, I reworded the output format message. Both the `default` and the `possible values` are programmatic and clap will print them anyways, there is no reason to include the same detail again in the help message.
This helps us avoid inconsistencies between functionality, code that clap makes use of, and freeform description that clap doesn't have knowledge about.
I alsoi changed the default output format of two other subcommands to be `json-pretty` rather than `text` to align with the rest of the subcommands.
Now every subcommand has the exact same output format help:
```
Options:
-t, --output-format <OUTPUT_FORMAT>  Output format of the result [default: json-pretty] …
```
> unitctl: clean up output format text

- tools/unitctl/README.md
- tools/unitctl/unit-client-rs/src/unitd_docker.rs
- tools/unitctl/unitctl/src/cmd/instances.rs
- tools/unitctl/unitctl/src/unitctl.rs
* default behavior is now a read write application mount
* user can specify a flag (-r) to mount app dir as read only
* fixes #1247
> tools/unitctl: make application directory configurable

- fuzzing/nxt_basic_fuzz.c
- fuzzing/nxt_http_controller_fuzz.c
- fuzzing/nxt_http_h1p_fuzz.c
- fuzzing/nxt_http_h1p_peer_fuzz.c
- fuzzing/nxt_json_fuzz.c
* djb hash
* murmur hash2
* parse
* sha1
* uri decode, uri encode
* utf8 casecmp
* websocket base64 encode
* websocket frame
* nxt_http_controller_fuzz.c
* nxt_http_h1p_peer_fuzz.c
* nxt_http_h1p_fuzz.c
* nxt_json_fuzz.c
[Null  dereference](https://oss-fuzz.com/testcase-detail/4522566136430592) in `nxt_http_h1p_fuzz.c`. https://github.com/nginx/unit/pull/1372/commits/5945e2bbfe610b699cd143871ce8a90b5c70226c
Added extra surface for fuzzer in `nxt_json_fuzz.c` by using `nxt_conf_json_length` API.
> fuzzing: added new target, fixed harness bug and beautified

- .editorconfig
- CONTRIBUTING.md
The first patch is a preparatory patch that just re-flows some of the text.
The second patch updates the 'Git Style Guide' section to reflect current reality as it currently gives potential contributors a lot of wrong information.
> Update CONTRIBUTING.md to reflect current reality

- .editorconfig
This just sets some basic file properties; character encoding, line endings, tabs vs spaces etc and is _not_ a replacement for a code formatter like indent(1) or clang-format.
> Add a basic .editorconfig file

- pkg/deb/Makefile
It's possible to have two versions of the same package installed on debian-based multiarch systems - e.g. i386 alongside amd64.  This means that when getting the package status through dpkg-query we'd get a duplicated string:
% dpkg-query -f '$${db:Status-Status}' -W libssl-dev $installed$installed
% dpkg -l | grep libssl-dev
ii  libssl-dev:amd64                 3.0.11-1~deb12u2               amd64        Secure Sockets Layer toolkit - development files
ii  libssl-dev:i386                  3.0.11-1~deb12u2               i386         Secure Sockets Layer toolkit - development files
The fix is to explicitely check for the main architecture and, in case for noarch (or rather all-arch in debian terms) packages, check for special :all architecture as well.
> Packaging: fix build-depends on multiarch debian systems

- docs/unit-openapi.yaml
The first patch updates the URL as it was renamed to be more accurate in what /status represents.
The second patch add entries for the new /status/modules endpoint which lists the currently loaded language modules.
[ This work was instigated by @Jcahilltorre hence the authorship of the patches... ]
> Update Openapi specification for new /status/modules endpoint

- auto/sched
- configure
- src/nxt_lib.c
This pull-request enhances how we determine the number of CPU's available to Unit to run on under Linux.
In a recent [discussion](https://github.com/nginx/unit/issues/1042#issuecomment-2282308293) it became clear there are cases whereby we can end up creating way too many router threads (these are what handle client connections).
We currently try to create a number of router threads (not incl the main one) that match the number of on-line CPU's. This is currently determined with
```c
n = sysconf(_SC_NPROCESSORS_ONLN);
```
While that generally works, there are cases where it can give the wrong answer, for us anyway. I'll use the nproc(1) utility to demonstrate
```sh
$ nproc 
4
$ taskset -c 0-1 nproc 
2
$ taskset -c 0-1 nproc --all
4
```
nproc with no arguments will (on Linux) use …
> Better available CPU count determination on Linux

- src/nxt_conf_validation.c
- src/nxt_router.c
Unit generally creates an extra number of router threads (to handle client connections, not incl the main thread) to match the number of available CPUs.
There are cases when this can go wrong, e.g on a high CPU count machine and Unit is being effectively limited to a few CPUs via the cgroups cpu controller. So Unit may create a large number of router threads when they are only going to effectively run on a couple of CPUs or so.
There may be other cases where you would like to tweak the number of router threads, depending on your workload.
As it turns out it looks like it was intended to be made configurable but was just never hooked up to the config system.
This adds a new '/settings/router/threads' config option which can be set like
```
{
"listen": {
...
},
"settings": {
"router": { …
```
> router: Make the number of router threads configurable

- src/nxt_listen_socket.h
On FreeBSD, OpenBSD & macOS we use a default listen(2) backlog of -1 which means use the OS's default value.
On Linux (and others) we used a hard coded value of 511, presumably due to this comment
```c
/* Linux, Solaris, and NetBSD treat negative value as 0. */
```
On Linux (at least since 2.4), this is wrong, Linux treats -1 (and so on) as use the OS's default (net.core.somaxconn). See this code in net/socket.c::__sys_listen()
```c
if ((unsigned int)backlog > somaxconn)
backlog = somaxconn;
```
On Linux prior to 5.4 somaxconn defaulted to 128, since 5.4 it defaults to 4096.
We've had complaints that a listen backlog of 511 is too small. This would help in those cases.
Unless they are on an old Kernel, in which case it's worse, but then the plan is to also make this configurable. This …
> socket: Use a default listen backlog of -1 on Linux

- src/nxt_conf_validation.c
- src/nxt_router.c
@oopsoop2 on GitHub reported a performance issue related to the default listen(2) backlog size of 511 on nginx. They found that increasing it helped, nginx has a config option to configure this.
They would like to be able to do the same on Unit (which also defaults to 511 on some systems, incl Linux). This seems reasonable.
This adds a new per-listener 'backlog' config option, e.g
```
{
"listeners": {
"[::1]:8080": {
"pass": "routes",
"backlog": 1024
},
}
...
}
```
This doesn't effect the control socket.
> conf, router: Make the listen(2) backlog configurable

- src/nxt_conf_validation.c
- src/nxt_http.h
- src/nxt_http_request.c
- src/nxt_http_return.c
- src/nxt_http_rewrite.c
- src/nxt_http_route.c
- src/nxt_http_set_headers.c
- src/nxt_http_static.c
- src/nxt_router.h
- src/nxt_router_access_log.c
- src/nxt_tstr.c
- src/nxt_tstr.h
- src/nxt_var.c
- test/test_routing.py
Two things:
1. restrict variables to only support synchronous way.
Initially, variable query was designed to accomodate both synchronous and asynchronous operations. However, upon consideration of actual requirements, we recognized that asynchronous support was not needed.
This refactoring is intended to simplify the usage of variable queries and prepare for the subsequent feature of variable updating.
2. Add if option to match object to make matching scripting. For example:
```
{
"listeners": {
"*:8080": {
"pass": "routes"
}
},
"routes": [
{
"match": {
"if": "!`${headers['User-Agent'].split('/')[0] == 'curl'}`"
},
"action": {
"return": 204
}
}
]
}
```
> Add "if" option to the "match" object.

- .github/workflows/unitctl.yml
unitctl makes use of 'docs/unit-openapi.yaml' so be sure to run these checks if that file changes.
> ci/unitctl: Update paths

- docs/unit-openapi.yaml
Add entries for the new 'backlog' and 'listen_threads' config options introduced in commits 57c88fd40 ("router: Make the number of router threads configurable") and 76489fb7e ("conf, router: Make the listen(2) backlog configurable").
> docs/openapi: Add new config options

- fuzzing/nxt_http_h1p_peer_fuzz.c
- src/nxt_sockaddr.c
The first patch is straightforward; https://github.com/nginx/unit/pull/1393/commits/69b830bf75b0c0d40c0cde003b45b87a78170ba7 [70961](https://oss-fuzz.com/testcase-detail/4875165201137664).
The second patch, on the other hand, is quite suspicious. It works now, but I have no idea what I am doing.
I think it does require some changes to the JSON parsing and JSON after parsing.
https://github.com/nginx/unit/pull/1393/commits/0d581e81f4a873fedebb8289e3af2267c6392f28 [70961](https://oss-fuzz.com/testcase-detail/4875165201137664)
The `addr->length` is `0`. It does make my job easy, so I added a check: if the length is zero, return null.
But `addr->start` holds 303 bytes.
```patch
diff --git a/src/nxt_sockaddr.c b/src/nxt_sockaddr.c
index 32941893..c48e0662 100644
--- a/src/nxt_sockaddr.c
+++ …
```
> fuzzing: fixed harness bug

- pkg/contrib/tarballs/.gitignore
This directory is needed for contribs to function.
> Added .gitignore for pkg/contrib/tarballs

- src/wasm-wasi-component/Cargo.lock
- src/wasm-wasi-component/Cargo.toml
- src/wasm-wasi-component/src/lib.rs
This PR bumps the libwasmtime version used in both the wasm and wasm-wasi-component modules to version 24.
This PR adds additions to the tooling to properly build  libwasmtime for the wasm module. This introduces the need for cmake on the host. Dockerfiles are not updated to reflect this as part of this PR.
Fixes: https://github.com/nginx/unit/issues/1392
> bump wasmtime to v24

- .github/workflows/unitctl.yml
- Adds `unitctl/` prefix to tags generated by manual workflow runs. Previously, only release titles (but not tags) were prefixed.
- Omits superfluous `name` field; falls back to `tag` when absent.
- Removes unnecessary conditional from `prelease` field.
This results in the following tagging / releasing behavior:
1. Running manually creates a pre-release and tags it `unitctl/VERSION`
2. Pushing a tag formatted like `x.y.z` creates a normal release
Refines: 3501a50ffb93756e145295021ff9313ac77f1ba9
> ci: Fix tags on ad hoc unitctl releases

- .github/workflows/ci.yml
This comprises a couple of fixes to the CI.
1) Fix the wasmtime C API include/lib paths which recently changed with the update to wasmtime v24.
2) Run the CI when anything under src/contrib is changed (which _would_ have caught the above).
> ci: Fix wasmtime paths in ci.yml

- src/nxt_h1proto.c
- src/nxt_http_proxy.c
When the client closes the connection before the upstream, the proxy's error handler was calling cleanup operation like peer close and requestclose twice, this fix ensures the cleanup is performed only once, improving proxy stability.
Closes: https://github.com/nginx/unit/issues/828
> http: Fix router process crash whilst using proxy

- src/python/nxt_python.c
On some Python 3.11 systems, 3.11.9 & 3.11.10, we were seeing a crash
triggered by Py_Finalize() in nxt_python_atexit() when running one of
our pytests, namely
test/test_python_factory.py::test_python_factory_invalid_callable_value
2024/09/12 15:07:29 [alert] 5452#5452 factory "wsgi_invalid_callable" in module "wsgi" can not be called to fetch callable
Fatal Python error: none_dealloc: deallocating None: bug likely caused by a refcount error in a C extension
Python runtime state: finalizing (tstate=0x00007f560b88a718)
Current thread 0x00007f560bde7ad0 (most recent call first):
<no Python frame>
2024/09/12 15:07:29 [alert] 5451#5451 app process 5452 exited on signal 6 (core dumped)
This was due to
```c
obj = PyDict_GetItemString(PyModule_GetDict(module), callable);
```
in …
> python: Don't decrement a reference to a borrowed object

- tools/unitctl/README.md
- tools/unitctl/unitctl/src/main.rs
- tools/unitctl/unitctl/src/unitctl.rs
This PR achieves three separate things:
* cleans up some grouping of args with its commands to separate it from the next commands
* renamed the app to apps. Clap picks up the name of the enum as the subcommand name absent a command argument. I chose to rename the enum rather than add an option
* adds the apps line to the readme
It does not fix the whole of the readme, that's a separate issue and PR.
Closes #1423
> unitctl: rename app to apps

- tools/unitctl/README.md
- tools/unitctl/unitctl/src/cmd/applications.rs
- tools/unitctl/unitctl/src/unitctl.rs
This renames the 'app reload' subcommand to 'app restart'
Fixes #1426
> tools/unitctl: change reload to restart

- auto/cc/test
Due to 'char' (unless explicitly set) being signed or unsigned depending
on architecture, e.g on x86 it's signed, while on Arm it's unsigned,
this can lead to subtle bugs such if you use a plain char as a byte
thinking it's unsigned on all platforms (maybe you live in the world of
Arm).
What we can do is tell the compiler to treat 'char' as unsigned by
default, thus it will be consistent across platforms. Seeing as most of
the time it doesn't matter whether char is signed or unsigned, it
really only matters when you're dealing with 'bytes', which means it
makes sense to default char to unsigned.
The Linux Kernel made this change at the end of 2022.
This will also allow in the future to convert our u_char's to char's
(which will now be unsigned) and pass them directly into the libc …
> Compile with -funsigned-char

- src/nxt_time_parse.c
- src/test/nxt_term_parse_test.c
```
The following changes since commit ba234b4db2d137b7dcf63188cc19e0493ebbc01a:
Version bump (2024-09-17 22:42:09 +0100)
are available in the Git repository at:
git@github.com:ac000/unit.git ca-fix
for you to fetch changes up to bba84a73a259b7cb93e3c0a52a0aa7253e53042c:
src/test: Add an extra test case to nxt_term_parse_test.c (2024-09-24 14:55:04 +0100)
----------------------------------------------------------------
The first patch fixes a clang-analyzer and coverity issue where we assign
a value and then assign again without using it inbetween.
The second patch adds a test case for strings with trailing whitespace.
----------------------------------------------------------------
Andrew Clayton (2):
Resolve unused assignment in nxt_term_parse()
src/test: Add an extra test case to …
```
> Fix an unused variable issue in nxt_term_parse() as found by clang-analyzer and coverity

- tools/unitctl/Cargo.lock
- tools/unitctl/unit-client-rs/Cargo.toml
- tools/unitctl/unit-client-rs/src/lib.rs
- tools/unitctl/unit-client-rs/src/unit_client.rs
- tools/unitctl/unit-client-rs/src/unitd_docker.rs
This PR contains commits to fix both https://github.com/nginx/unit/issues/1439 and https://github.com/nginx/unit/issues/1438.
The OpenSSL issue is solved by moving to hyper-rustls from hyper-tls. 
The docker client error (hyper legacy client connect error) is solved by bumping the bollard library version and also just in case I have elaborated on the error print text.
Both issues were tested on Debian latest docker image (x86_64) as well as M1 (aarch64) OSX.
Help verifying on an aarch64 Linux box is welcome, but I expect similar results.
> unitctl: fixes for openssl and docker client

- src/nxt_process.c
There has been a long standing clang-analyzer issue in nxt_process_check_pid_status(), well ever since I introduced this function in commit b0e2d9d0a ("Isolation: Switch to fork(2) & unshare(2) on Linux."),
It is complaining that there are cases where 'status' could be returned with an undefined or garbage value.
Now I'm convinced this can't happen
```
If nxt_process_pipe_timer() returns NXT_OK
read(2) the status value
If the read(2) failed or if we got NXT_ERROR from
nxt_process_pipe_timer(), NXT_OK (0) and NXT_ERROR (-1) are the only
possible return values here, then we set status to -1
```
I don't see a scenario where status is either not set by the read(2) or not set to -1.
Now I'm not a fan of initialising variables willy-nilly, however, in this case if we initialise status to -1, …
> Re-work nxt_process_check_pid_status() slightly (resolves a clang-analyzer (non-)issue)

- .github/workflows/ci.yml
This pull-request compreises three patches fixing various issues with the CI due to the runners moving to Ubuntu 24.04 (though they seem to have sinnce reverted back, but we may as well keep these fixes...)
The first patch fixes the disabling of the mono service which may or may not be installed.
The second patch fixes the installation of pytest by installing it via the apt(8) package manager.
The third drops PHP 8.1 from our tests. See the commit message for the gory details.
> ci: Various fixes for update to Ubuntu 24.04

- src/perl/nxt_perl_psgi.c
In the perl language module we create a new perl *module* on the fly comprised of some preamble, the specified perl script and some post-amble.
In the preamble we create a constructor called new(), however this can clash with other constructors also called new.
While this can be worked around by instead of doing
... new CLASS
rather do
... CLASS->new()
While this constructor was added in commit 3b2c1d0e ("Perl: added implementation delayed response and streaming body."), I don't see that we actually use it anywhere (nor is it seemingly something we document) and if we simply remove it then things still seem to work, including the Perl pytests
...
test/test_perl_application.py::test_perl_streaming_body_multiple_responses[5.38.2] PASSED
... …
> perl: Remove unused module constructor

- src/nxt_js.c
- src/nxt_js.h
- src/nxt_router_access_log.c
- src/nxt_tstr.c
- src/nxt_tstr.h
When using JS configuration for the "format" option, access log entries
were being written without newline characters. This commit adds the
missing newline character to each log entry.
Closes: https://github.com/nginx/unit/issues/1458
> Fix missing newlines in access logs for JS configuration

- src/nxt_cert.c
- src/nxt_controller.c
- src/nxt_main_process.c
Mostly more 'static nxt_str_t ...'s
> Some more variable constification

- src/nxt_clang.h
```
sizeof() should never be used to get the size of an array.  It is
very unsafe, since arrays easily decay to pointers, and sizeof()
applied to a pointer gives false results that compile and produce
silent bugs.
It's better to use nxt_items(), which implements sizeof()
division, which recent compilers warn when used with pointers.
This change would have caught a couple of bugs that were *almost*
introduced
First up is the _infamous_ ternary macro bug (yes, using the ternary
operator in a macro is of itself a bad idea)
nxt_str_set(&port, (r->tls ? "https://" : "http://"));
which in the macro expansion runs:
(&port)->length = nxt_length((r->tls ? : "https://" : "http://"));
which evaluates to:
port.length = sizeof(r->tls ? "https://" : "http://") - 1;
which evaluates to:
port.length = 8 - …
```
> Use nxt_nitems() instead of sizeof() for strings (arrays)

- src/test/nxt_base64_test.c
nxt_log_alert() was missing the nxt_str_t parameter as required by the %V format specifier.
This was found with the Unit clang-ast plugin.
> src/test: Fix missing parameter to nxt_log_alert() in nxt_base64_test()

- .github/workflows/clang-ast.yaml
```
This does compile-time type and argument checking using a clang-plugin.
It was run as part of buildbot.
This covers unitd, src/test and the php, perl, python, ruby, wasm, java
and nodejs language modules/support.
It doesn't cover Go as that doesn't build anything with clang (uses
cgo) or wasm-wasi-component as that uses rustc.
Link: <https://github.com/nginx/clang-ast/tree/unit>
```
> ci: Add a clang-ast workflow

- auto/threads
```
When configuring under Linux we always got the following
checking for pthread spinlock zero initial value ... found but is not working
Having *actually* taken a look at this, this check seems somewhat bogus,
the first thing it does is
pthread_spinlock_t  lock = 0;
which you shouldn't do anyway, you should use pthread_spin_init(3) to
initialise the pthread_spinlock_t variable.
But in any case, this thing, NXT_HAVE_PTHREAD_SPINLOCK_ZERO, isn't even
checked for in the code.
Neither is NXT_HAVE_PTHREAD_SPINLOCK, we don't use the pthread_spin_*
API, but rather roll our own spinlock implementation.
So let's just remove these checks, at the very least it'll speed
./configure up!
```
> auto: Remove unused pthread spinlock checks

- src/wasm-wasi-component/Cargo.lock
- src/wasm-wasi-component/Cargo.toml
```
This fixes an issue we had with wasm-wasi-component failing to load components with
2024/11/06 21:08:50 [alert] 107196#107196 failed to create initial state
Caused by:
0: failed to compile component
1: WebAssembly translation error
2: Invalid input WebAssembly code at offset 15936: zero byte expected
Which was a symptom of
<https://github.com/bytecodealliance/wasmtime/issues/9130>
Closes: https://github.com/nginx/unit/issues/1477
```
> wasm-wc: Update to wasmtime v26.0.1

- src/nxt_conf_validation.c
- src/nxt_router.h
- src/nxt_router_access_log.c
- src/nxt_tstr.c
- src/nxt_tstr.h
- test/test_access_log.py
Allow format to be an object to generate JSON logs. The object keys
become JSON field names, and values support string, variable, and JS.
Note that when there is no JS in the format values, the object will
be pre-serialized to a JSON template string at configuration phase
for better performance.
Example config:
```
{
"access_log": {
"path": "/tmp/access.log",
"format": {
"remote_addr": "$remote_addr",
"time_local": "$time_local",
"request_line": "$request_line",
"status": "$status",
"body_bytes_sent": "$body_bytes_sent",
"header_referer": "$header_referer",
"header_user_agent": "$header_user_agent"
}
}
}
```
> http: JSON format access logging support

- src/nxt_string.h
```
Decast nxt_cpymem()
nxt_cpymem() is basically mempcpy(3)
Like mempcpy() nxt_cpymem() returns a void *.
nxt_cpymem() is implemented as a wrapper around memcpy(3), however
before returning the new pointer value we cast the return of memcpy(3)
to a u_char *, then add the length parameter to it.
I guess this was done to support compilers that do not support
arithmetic on void pointers as the C standard forbids it.
However since we removed support for compilers other than GCC and Clang
(ending in commit 9cd11133 ("Remove support for Sun's Sun Studio/SunPro
C compiler")) this is no longer an issue as both GCC and Clang support
arithmetic on void pointers (without the -pedantic option).
While removing the unnecessary casting in this case doesn't necessarily
improve type-safety (as we're …
```
> Decast nxt_cpymem()

- .github/workflows/ci-dev-distro-compiler.yaml
```
This just builds the OTEL stuff for the Fedora Rawhide and Alpine Edge
distributions.
If we ever get test cases covering OTEL we can figure out the best way
to do it in the ci.yaml, but right now I don't see the point in building
OTEL in every test configuration there...
```
> ci: Build with --otel on dev distros

- src/otel/src/lib.rs
otel: Disable static_mut_refs warning for nxt_otel_rs_span_tx()
When compiling OTEL support with rustc 1.83.0 we started getting the
following warning
Compiling otel v0.1.0 (/home/andrew/src/unit/src/otel)
warning: creating a mutable reference to mutable static is discouraged
--> src/lib.rs:42:9
|
42 |         SPAN_TX.take();
|         ^^^^^^^^^^^^^^ mutable reference to mutable static
|
= note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
= note: mutable references to mutable statics are dangerous; it's undefined behavior if any other pointer to the static is used or if any other reference is created for the static while the mutable reference lives
= note: `#[warn(static_mut_refs)]` on by default
warning: `otel` (lib) …
> otel: Disable static_mut_refs warning for nxt_otel_rs_span_tx()

- pkg/docker/Dockerfile.php8.4
- pkg/docker/Dockerfile.python3.13
- pkg/docker/Dockerfile.python3.13-slim
- pkg/docker/Makefile
Note that this updates the version in the master branch; the commits to add (and not replace the older versions) will be in a separate push to `packaging` branch as discussed in https://github.com/nginx/unit/issues/1453
> Docker: update Python and PHP versions

- pkg/rpm/Makefile
In 4.20, rpm changed the way build roots are named.  Our packaging relies on the symlinks being created as a part of a rule to make sure targets are being built correctly.
This patch implements (a hacky) way to check what the build root should be named on a currently running rpm version and adjusts the symlinks accordingly.
> Packages: support rpm 4.20+

- pkg/rpm/Makefile
- pkg/rpm/Makefile.jsc-common
- pkg/rpm/Makefile.jsc17
- pkg/rpm/Makefile.jsc21
- pkg/rpm/Makefile.python313
- pkg/rpm/rpmbuild/SOURCES/unit.example-jsc21-config
- pkg/rpm/rpmbuild/SOURCES/unit.example-python313-config
While at it, removed support for Fedora 39 as it's EOL.
> Packages: added Fedora 41 support.

- auto/otel
```
auto/otel: Remove pkg-config check
@thresheek reported an issue trying to configure OTEL support on Amazon
Linux 2
checking for OTEL requirements:
- checking for rust compiler ... found
- checking for cargo ... found
- checking for OpenSSL library ... found
Package openssl was not found in the pkg-config search path.
Perhaps you should add the directory containing `openssl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'openssl' found
We successfully built the test program with '-lssl -lcrypto', but then
tried to use 'pkg-config openssl --cflags --libs' to override
NXT_OTEL_LIBS.
On Amazon Linux2 there is no openssl.pc, they have a openssl11.pc.
Let's just remove the pkg-config check, if we get here, we have
successfully built with '-lssl -lcrypto', so just go with that …
```
> auto/otel: Remove pkg-config check

- src/wasm-wasi-component/Cargo.lock
```
wasm-wc: Update crates
Run 'cargo update' to get the latest version of the required crates in
preparation for the 1.34.0 release.
This resolves a dependabot notification regarding 'idna'.
Link: <https://github.com/nginx/unit/security/dependabot/13>
```
> wasm-wc: Update crates

- src/nxt_otel.c
Fixes #1523 and #1526 by adding null checks to cover unconfigured OpenTelemetry cases.
Both tests and traffic were tested on both x86_64 Linux and arm64 Linux.
> otel: fix segfaults when otel not configured

- src/nxt_http_static.c
Associate file extension `.mjs` with `application/javascript`.
Context: common output of static site generators. There's little risk of ambiguity for this extension, so might as well support it out of the box.
> [nxt_http_static] add `.mjs` extension to default_types

- src/ruby/nxt_ruby_stream_io.c
```
ruby: Fix build failures with Ruby 3.4
Ruby 3.4 started to actually mark some deprecated functions as
*deprecated* now resulting in compiler warnings (which due to -Werror we
treat as errors and thus the build fails).
The *new* functions were actually introduced back in Ruby 1.9.2, so have
been around for quite some time. We claim support for Ruby 2.0 onwards
so this is more than fine.
The new API replaces the old 'mark' and 'free' parameters with a struct
that allows for more fine tuning/configuration. We never made use of
either of those parameters and so the only members of this struct we
*need* to set is the structure wrapper name and the dsize function
pointer which is passed a pointer to the underlying wrapped structure to
calculate its memory usage. While this is *not* required …
```
> ruby: Fix build failures with Ruby 3.4

- auto/cc/test
```
Fix build with GCC 15
The upcoming GCC 15 release introduces a new compiler warning,
Wunterminated-string-initialization.
This is intended to catch things like
static const u_char  hex[16] = "0123456789ABCDEF";
Where we are creating a character array from a string literal, but the
specified size is not enough for the terminating NUL byte.
In the above example that is intended as it is used as a lookup table
and only the individual indices are accessed.
As it happens, Unit uses the above idiom in a few places, triggering
this warning (which we treat as an error by default).
While I don't like disabling compiler warnings, lets just disable this
one temporarily, as there is a patch in the works to make the
"nonstring" variable attribute quell this warning.
We just disable this on GCC as …
```
> Fix build with GCC 15

- src/python/nxt_python_asgi.c
```
python: Fix Litestar WebSockets compatibility
It was reported on GitHub that Unit was unable to work with WebSockets
under Litestar Python applications.
This was due to Unit sending a 'method' variable in the WebSocket's
connection scope, which Litestar was interpreting as being a normal HTTP
connection.
The ASGI WebSocket specification makes no mention about setting a
'method', so let's not send it on WebSockets.
Also tested this change with basic ASGI WebSockets and FastAPI
WebSockets and obviously pytests still pass.
Closes: https://github.com/nginx/unit/issues/1507
Link: <https://asgi.readthedocs.io/en/latest/specs/www.html#websocket-connection-scope>
```
> python: Fix Litestar WebSockets compatibility

- src/nxt_h1proto.c
```
http: Fix WebSockets with Firefox
Firefox (going back a couple of years at least) was unable to open a
WebSocket connection to Unit due to it sending a Connection header of
Connection: keep-alive, Upgrade
However in Unit we were expecting only a single value in the header.
Fix the 'Connection' parsing in nxt_h1p_connection() to address this.
Closes: https://github.com/nginx/unit/issues/772
```
> http: Fix WebSockets with Firefox

- .github/workflows/cifuzz.yml
```
ci: Update to actions/upload-artifact@v4 in cifuzz.yml
We need to update to the latest version of actions/upload-artifact in
cifuzz.yml due to the workflow failing because of
Error: This request has been automatically failed because it uses a
deprecated version of `actions/upload-artifact: v3`. Learn more:
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```
> ci: Update to actions/upload-artifact@v4 in cifuzz.yml

- src/java/nginx/unit/websocket/WsFrameBase.java
This pull-request comprises two patches.
* java: websocket: Fix calculation of payload length for > 32bit values
This fixes a calculation that was done as an `int` when it should have been treated as a `long`.
* java: websocket: Additional payload length validation
This adds a check for negative payload lengths.
Both these patches were applied to the Apache Tomcat sources a number of years ago. Original patch links are in the commit messages.
```
The following changes since commit 3fea47eaa3edd916ecf0b339626dd5f963838295:
python: Add Django 5.x compatibility (2025-02-21 01:20:31 +0000)
are available in the Git repository at:
git@github.com:ac000/unit.git java
for you to fetch changes up to d7afeb2b94f1cd72ed02403609e5484f9514e5eb:
java: websocket: Additional payload length validation …
```
> A couple of java websocket fixes

- pkg/docker/Dockerfile.go1.24
- pkg/docker/Makefile
Official images check for outdated references in images so we have to update golang image we use.
https://github.com/docker-library/official-images/pull/18559
While at it: git desc doesn't work well with lightweight tags. So replaced it with rev-parse which gives proper results.
IIRC we did similar substitution for other docker projects somewhere.
> Packaging: update docker golang version. Remove unsupported 1.22, add newer 1.24

- auto/cc/test
- auto/clang
- src/nxt_clang.h
- src/nxt_http_parse.c
- src/nxt_http_parse.h
- src/nxt_sprintf.c
- src/nxt_string.c
As previously promised, this PR comprises three commits that allow us to re-enable the new GCC 15 warning `Wunterminated-string-initialization`.
* The first commit adds a wrapper around `__attribute__ ((__nonstring__))`
As a reminder, this attribute is used to mark character arrays that are intentionally not NUL terminated.
* The second commit tags various character arrays with this attribute.
* The third commit removes the disabling of this new warning.
```
The following changes since commit d7afeb2b94f1cd72ed02403609e5484f9514e5eb:
java: websocket: Additional payload length validation (2025-02-21 22:49:15 +0000)
are available in the Git repository at:
git@github.com:ac000/unit.git wusi
for you to fetch changes up to ca60536172916b7c3e4ff62e20be1ae2f3de039d:
auto/cc: gcc: Don't disable …
```
> Tag some char arrays with __attribute__ ((__nonstring__))

- test/test_tls.py
- test/test_tls_sni.py
```
tests: Fix TLS tests with Python 3.13
Python 3.13 sets the VERIFY_X509_STRICT flag by default in
create_default_context().
This breaks our TLS tests with dummy certificates. Remove this flag.
Thanks to @zfouts for the hint about the flag.
As an aside there is another Python 3.13 change which breaks the tests,
in that the cgi module has been removed. However there is a legacy-cgi
module you can install to get things going again (note this module is
unmaintained). E.g. In Fedora 'dnf install python3-legacy-cgi'.
Reported-by: Konstantin Pavlov <thresh@nginx.com>
Closes: https://github.com/nginx/unit/issues/1545
Link: <https://docs.python.org/3/whatsnew/3.13.html#ssl>
Link: <https://docs.python.org/3.13/library/cgi.html>
```
> tests: Fix TLS tests with Python 3.13

- src/nxt_socket_msg.h
- src/nxt_unit.c
While tracking down some memory leaks valgrind(1) was highlighting numerous issues. Including the following
```
==166470== Syscall param sendmsg(msg.msg_iov[0]) points to uninitialised byte(s)
==166470==    at 0x4AE6514: sendmsg (sendmsg.c:28)
==166470==    by 0x42D86C: nxt_sendmsg (nxt_socket_msg.c:32)
==166470==    by 0x4FE6695: nxt_unit_sendmsg (nxt_unit.c:6013)
==166470==    by 0x4FEB6E2: nxt_unit_ready (nxt_unit.c:963)
==166470==    by 0x4FEB6E2: nxt_unit_init (nxt_unit.c:557)
==166470==    by 0x4FEEC56: nxt_php_start (nxt_php_sapi.c:507)
==166470==    by 0x426BA0: nxt_app_setup (nxt_application.c:1029)
==166470==    by 0x403153: nxt_process_do_start (nxt_process.c:718)
==166470==    by 0x4042A3: nxt_process_whoami_ok (nxt_process.c:846)
==166470==    by 0x407A28: …
```
> Properly initialise some structures

- src/nxt_http_compression.c
- src/nxt_http_compression.h
- src/nxt_router.c
```
http: Compress application responses
This adds initial support for compressing application responses.
A couple of things to note
1) Compressed responses are sent 'chunked' as we don't know beforehand
how large the compressed response will be.
2) We only compress responses where we know the Content-Length as we
need to check with the 'min_length' config parameter. It's also
currently how we track when we need to close the compression stream
off.
Co-authored-by: Alejandro Colomar <alx@kernel.org>
Signed-off-by: Alejandro Colomar <alx@kernel.org>
```
> http: Compress application responses

- test/test_tls_sni.py
`alt_names` should be an array of strings, and when it is a string it ends with `openssl.conf` which contains:
```
[alt_names]
DNS.1 = s
DNS.2 = a
DNS.3 = m
DNS.4 = e
DNS.5 = .
DNS.6 = a
DNS.7 = l
DNS.8 = t
DNS.9 = n
DNS.10 = a
DNS.11 = m
DNS.12 = e
DNS.13 = .
DNS.14 = c
DNS.15 = o
DNS.16 = m
```
what may work or fail, which depends on OpenSSL library because `.` can be trated as empty string.
Before creating a PR, run through this checklist and mark each as complete:
> Fixed `alt_names` at `test_tls_sni_same_alt`

- src/nxt_openssl.c
Fixes #1600
The `test_tls_certificate_change` test likely uses Python's `ssl.get_server_certificate` function to retrieve the server's TLS certificate before and after changing it. This function establishes an SSL connection, retrieves the certificate, and then closes the connection without performing a proper SSL shutdown (i.e., sending a `close_notify` alert). On the server side, when `SSL_shutdown` is called during cleanup, it attempts to send its own `close_notify` alert but fails because the client has already closed the socket, resulting in the "Broken pipe" error (`EPIPE`). These errors are logged as alerts, and since they aren't skipped, the test fails during teardown when `Log.check_alerts asserts` that no unskipped alerts remain.
Before creating a PR, run through this checklist …
> Treat a “broken pipe” on SSL_shutdown() as a normal close

- auto/modules/wasm
```
auto/modules/wasm: Remove an unneeded compiler option
-Wno-missing-field-initializers was needed for GCC 4.8 / RHEL 7 etc to
avoid warnings with {} empty initialisers.
We haven't needed to support that compiler for sometime.
```
> auto/modules/wasm: Remove an unneeded compiler option

- auto/compression
auto/compression: Error out if requested library not found
You asked for a specific compression library, be clear when it isn't
found.
> auto/compression: Error out if requested library not found

- .github/workflows/ci-dev-distro-compiler.yaml
- .github/workflows/ci.yml
ci: Build Unit with --zlib --zstd --brotli
This just does a build test of building Unit with support for zlib
(deflate & gzip), zstd and brotli HTTP compression.
> ci: Build Unit with --zlib --zstd --brotli

- .github/workflows/clang-ast.yaml
ci: clang-ast: Update to openjdk-21-jdk
Seems OpenJDK 17 is no longer available in Debian testing.
> ci: clang-ast: Update to openjdk-21-jdk

- src/otel/Cargo.lock
- src/wasm-wasi-component/Cargo.lock
- src/wasm-wasi-component/Cargo.toml
- src/wasm-wasi-component/src/lib.rs
- tools/unitctl/Cargo.lock
This pull-request updates the various rust components (otel, unitctl &
wasm-wasi-component) to the latest versions of their required crates.
wasm-wasi-component is also updated to the latest version of Wasmtime
(35.0.0) which required some changes.
This is part of getting ready for a 1.35.0 release of Unit.
```
The following changes since commit c8b859e373089d3f347efb806c9926823de41bf6:
Set SERVER_PORT appropriately (2025-07-25 04:49:45 +0100)
are available in the Git repository at:
git@github.com:ac000/unit.git crates-update
for you to fetch changes up to 45da9d1da5002d08981ed32b215547b55be90038:
wasm-wc: Update to wasmtime 35.0.0 (2025-07-25 22:46:32 +0100)
----------------------------------------------------------------
Andrew Clayton (4):
otel: Update crates
tools/unitctl: Update …
```
> crates update

- src/nxt_http_compression.c
- src/nxt_http_compression.h
- src/nxt_http_static.c
```
This pull-request comprises two commits
1) http: compression: Set the temporary file name in n_h_c_c_s_r()
The sets the temporary compressed file name in the nxt_file_t structure.
While we don't actually need it ourselves, it's used in the case that
nxt_file_close() fails.
2) http: compression: Add a missed nxt_http_comp_compress() return check
This adds a missing check for compression errors when compressing static
responses.
----------------------------------------------------------------
Andrew Clayton (2):
http: compression: Set the temporary file name in n_h_c_c_s_r()
http: compression: Add a missed nxt_http_comp_compress() return check
src/nxt_http_compression.c | 26 ++++++++++++++++----------
src/nxt_http_compression.h |  4 ++--
src/nxt_http_static.c      |  2 +-
3 files …
```
> A couple of HTTP compression fixes

- src/nxt_php_sapi.c
The `diable_classes` is deprecated since PHP 8.5, see https://github.com/php/php-src/commit/f4e2e91d4b6d28448104500819b68edf58bd263c
Making this build conditional also require to change tests
Before creating a PR, run through this checklist and mark each as complete:
> Fix building with PHP 8.5

- src/nxt_php_sapi.c
Since PHP 8.5.0 RC1 the structure been updated #1660 
Before creating a PR, run through this checklist and mark each as complete:
> PHP 8.5 new SAPI callback pre_request_init
